name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.3.1
  go_router: ^16.3.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
